/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.Staff;
import BUS.StaffBUS;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author donha
 */
public class StaffManagement extends javax.swing.JFrame {

    /**
     * Creates new form BillManagement
     */
    StaffBUS staffBUS = new StaffBUS();
    ArrayList<Staff> staffls = staffBUS.getList();
    
    public StaffManagement() throws ClassNotFoundException {
        initComponents();
        staffBUS.listStaff();
        showTable(staffls);
    }
    
    private void showTable(ArrayList<Staff> staffls)
    {   
        tbl_Staff.removeAll();
        DefaultTableModel defaultModel = (DefaultTableModel) tbl_Staff.getModel();
        defaultModel.setRowCount(0);
        for(Staff s : staffls)
        {
            if(s.getStatus() == 1){
                int staffID = s.getStaffID();
                String firstName = s.getFirstName();
                String lastName = s.getLastName();
                String email = s.getEmail();
                String phone = s.getPhone();
                int authority = s.getAuthority();
                defaultModel.addRow(new Object[]{staffID, firstName, lastName, email, phone, authority});
            }
        }
    }
    
    private void showCustomerValue(ArrayList<Staff> staffls)
    {
        
        int row = tbl_Staff.getSelectedRow();
        int value = (int) tbl_Staff.getModel().getValueAt(row, 0);
        for(Staff s : staffls)
        {
            if (staffBUS.CheckStaffID(value))
            {
                jlb_staffID.setText(tbl_Staff.getModel().getValueAt(row, 0).toString());
                txt_firstName.setText(tbl_Staff.getModel().getValueAt(row, 1).toString());
                txt_lastName.setText(tbl_Staff.getModel().getValueAt(row, 2).toString());
                txt_email.setText(tbl_Staff.getModel().getValueAt(row, 3).toString());
                txt_phone.setText(tbl_Staff.getModel().getValueAt(row, 4).toString());
                txt_authority.setText(tbl_Staff.getModel().getValueAt(row, 5).toString());
            }
        }
    }
    
    private void delStaff(){
    int row = tbl_Staff.getSelectedRow();    
    try {    
      if(row < 0)
      {
        JOptionPane.showMessageDialog(new JFrame(), "Chọn sản phẩm cần xoá", "Dialog",
        JOptionPane.ERROR_MESSAGE);
        return; 
      }
         
      int staffID = (int)tbl_Staff.getModel().getValueAt(row, 0);
      String firstName = tbl_Staff.getModel().getValueAt(row, 1).toString();
      String lastName = tbl_Staff.getModel().getValueAt(row, 2).toString();
      String email = tbl_Staff.getModel().getValueAt(row, 3).toString();
      String phone = tbl_Staff.getModel().getValueAt(row, 4).toString();
      int authority = (int)tbl_Staff.getModel().getValueAt(row, 5);
      int status = 0;
      Staff s = new Staff(staffID, firstName, lastName, email, phone, authority, status);
      staffBUS.SetStaff(s);
      refresh();
      resetText();
      row = -1;
            
        } catch (ClassNotFoundException ex) { 
            Logger.getLogger(Staff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void resetText(){
        jlb_staffID.setText("...");
        txt_firstName.setText("");
        txt_lastName.setText("");
        txt_email.setText("");
        txt_phone.setText("");
        txt_authority.setText("");
    }
    
    private void refresh(){
        try {
            staffBUS.listStaff();
            staffls = staffBUS.getList(); 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CustomerManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
        showTable(staffls);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Staff = new javax.swing.JTable();
        btn_restore = new javax.swing.JToggleButton();
        btn_del = new javax.swing.JToggleButton();
        btn_Update = new javax.swing.JToggleButton();
        btn_Refresh = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        sdtJbl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tenkhachJlb = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        tenkhachJlb1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tenkhachJlb2 = new javax.swing.JTextField();
        jlb_staffID = new javax.swing.JLabel();
        jlb_firstName = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        jlb_lastName = new javax.swing.JLabel();
        txt_lastName = new javax.swing.JTextField();
        jlb_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_add1 = new javax.swing.JToggleButton();
        jlb_phone = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jlb_authority = new javax.swing.JLabel();
        txt_authority = new javax.swing.JTextField();
        jlb_staff = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Staff Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 300, 77));

        tbl_Staff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbl_Staff.setForeground(new java.awt.Color(255, 153, 51));
        tbl_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "staffID", "firstName", "lastName", "email", "phone","authority"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }

    );
    tbl_Staff.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
    tbl_Staff.setRowHeight(40);
    tbl_Staff.setRowMargin(2);
    tbl_Staff.setSelectionBackground(new java.awt.Color(153, 255, 153));
    tbl_Staff.setSelectionForeground(new java.awt.Color(0, 0, 0));
    tbl_Staff.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tbl_StaffMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tbl_Staff);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, 1270, 157));

    btn_restore.setBackground(new java.awt.Color(102, 255, 102));
    btn_restore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    btn_restore.setForeground(new java.awt.Color(255, 255, 255));
    btn_restore.setText("Khôi phục");
    btn_restore.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btn_restoreMouseClicked(evt);
        }
    });
    btn_restore.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_restoreActionPerformed(evt);
        }
    });
    jPanel1.add(btn_restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 230, 90));

    btn_del.setBackground(new java.awt.Color(255, 0, 0));
    btn_del.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    btn_del.setForeground(new java.awt.Color(255, 255, 255));
    btn_del.setText("Xóa");
    btn_del.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_delActionPerformed(evt);
        }
    });
    jPanel1.add(btn_del, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 610, 230, 90));

    btn_Update.setBackground(new java.awt.Color(102, 255, 102));
    btn_Update.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    btn_Update.setForeground(new java.awt.Color(255, 255, 255));
    btn_Update.setText("Sửa");
    btn_Update.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_UpdateActionPerformed(evt);
        }
    });
    jPanel1.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, 230, 90));

    btn_Refresh.setBackground(new java.awt.Color(102, 255, 255));
    btn_Refresh.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    btn_Refresh.setForeground(new java.awt.Color(255, 255, 255));
    btn_Refresh.setText("Làm Mới");
    btn_Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btn_RefreshMouseClicked(evt);
        }
    });
    btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_RefreshActionPerformed(evt);
        }
    });
    jPanel1.add(btn_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 610, 230, 90));

    jLabel3.setBackground(new java.awt.Color(255, 255, 255));
    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(255, 153, 51));
    jLabel3.setText("Search:");
    jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 146, 50));

    sdtJbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    sdtJbl.setForeground(new java.awt.Color(255, 153, 51));
    sdtJbl.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            sdtJblActionPerformed(evt);
        }
    });
    jPanel1.add(sdtJbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 190, 52));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 153, 51));
    jLabel5.setText("TeacherID:");
    jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 138, 52));

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(255, 153, 51));
    jLabel6.setText("HireDate:");
    jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 110, 52));

    tenkhachJlb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    tenkhachJlb.setForeground(new java.awt.Color(255, 153, 51));
    tenkhachJlb.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tenkhachJlbActionPerformed(evt);
        }
    });
    jPanel1.add(tenkhachJlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 250, 52));

    jSeparator1.setBackground(new java.awt.Color(255, 153, 51));
    jSeparator1.setForeground(new java.awt.Color(255, 153, 51));
    jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 1270, 10));

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel9.setForeground(new java.awt.Color(255, 153, 51));
    jLabel9.setText("Lastname:");
    jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 110, 52));

    tenkhachJlb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    tenkhachJlb1.setForeground(new java.awt.Color(255, 153, 51));
    tenkhachJlb1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tenkhachJlb1ActionPerformed(evt);
        }
    });
    jPanel1.add(tenkhachJlb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 200, 52));

    jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel10.setForeground(new java.awt.Color(255, 153, 51));
    jLabel10.setText("Firstname:");
    jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 110, 52));

    tenkhachJlb2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    tenkhachJlb2.setForeground(new java.awt.Color(255, 153, 51));
    tenkhachJlb2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tenkhachJlb2ActionPerformed(evt);
        }
    });
    jPanel1.add(tenkhachJlb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 200, 52));

    jlb_staffID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_staffID.setForeground(new java.awt.Color(255, 153, 51));
    jlb_staffID.setText("...");
    jPanel1.add(jlb_staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 138, 52));

    jlb_firstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_firstName.setForeground(new java.awt.Color(255, 153, 51));
    jlb_firstName.setText("FirstName:");
    jPanel1.add(jlb_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 110, 52));

    txt_firstName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txt_firstName.setForeground(new java.awt.Color(255, 153, 51));
    txt_firstName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_firstNameActionPerformed(evt);
        }
    });
    jPanel1.add(txt_firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 200, 52));

    jlb_lastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_lastName.setForeground(new java.awt.Color(255, 153, 51));
    jlb_lastName.setText("LastName:");
    jPanel1.add(jlb_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 270, 110, 52));

    txt_lastName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txt_lastName.setForeground(new java.awt.Color(255, 153, 51));
    txt_lastName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_lastNameActionPerformed(evt);
        }
    });
    jPanel1.add(txt_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 270, 200, 52));

    jlb_email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_email.setForeground(new java.awt.Color(255, 153, 51));
    jlb_email.setText("Email:");
    jPanel1.add(jlb_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 140, 52));

    txt_email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    txt_email.setForeground(new java.awt.Color(255, 153, 51));
    txt_email.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_emailActionPerformed(evt);
        }
    });
    jPanel1.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 250, 52));

    jSeparator2.setBackground(new java.awt.Color(255, 153, 51));
    jSeparator2.setForeground(new java.awt.Color(255, 153, 51));
    jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 1270, 10));

    btn_add1.setBackground(new java.awt.Color(102, 255, 102));
    btn_add1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
    btn_add1.setForeground(new java.awt.Color(255, 255, 255));
    btn_add1.setText("Thêm");
    btn_add1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            btn_add1MouseClicked(evt);
        }
    });
    btn_add1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btn_add1ActionPerformed(evt);
        }
    });
    jPanel1.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 230, 90));

    jlb_phone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_phone.setForeground(new java.awt.Color(255, 153, 51));
    jlb_phone.setText("Phone:");
    jPanel1.add(jlb_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 70, 52));

    txt_phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txt_phone.setForeground(new java.awt.Color(255, 153, 51));
    txt_phone.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_phoneActionPerformed(evt);
        }
    });
    jPanel1.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 200, 52));

    jlb_authority.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_authority.setForeground(new java.awt.Color(255, 153, 51));
    jlb_authority.setText("Authority:");
    jPanel1.add(jlb_authority, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 138, 52));

    txt_authority.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    txt_authority.setForeground(new java.awt.Color(255, 153, 51));
    txt_authority.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_authorityActionPerformed(evt);
        }
    });
    jPanel1.add(txt_authority, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 340, 200, 52));

    jlb_staff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jlb_staff.setForeground(new java.awt.Color(255, 153, 51));
    jlb_staff.setText("StaffID:");
    jPanel1.add(jlb_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 138, 52));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_StaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_StaffMouseClicked
//        showCourseValue();
    }//GEN-LAST:event_tbl_StaffMouseClicked

    private void btn_restoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_restoreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_restoreMouseClicked

    private void btn_restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restoreActionPerformed
//        CourseRecovery a = new CourseRecovery();
//        a.setVisible(true);

    }//GEN-LAST:event_btn_restoreActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        delStaff();

    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
//        editCourse();
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_RefreshMouseClicked
//        showTable();

    }//GEN-LAST:event_btn_RefreshMouseClicked

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void sdtJblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdtJblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdtJblActionPerformed

    private void tenkhachJlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenkhachJlbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenkhachJlbActionPerformed

    private void tenkhachJlb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenkhachJlb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenkhachJlb1ActionPerformed

    private void tenkhachJlb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenkhachJlb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenkhachJlb2ActionPerformed

    private void txt_firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstNameActionPerformed

    private void txt_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lastNameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void btn_add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_add1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_add1MouseClicked

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
//        AddCourse a = new AddCourse();
    try {
           AddStaff s = new AddStaff();
            s.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StaffManagement.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_add1ActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void txt_authorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_authorityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_authorityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window Vista".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StaffManagement().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StaffManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_Refresh;
    private javax.swing.JToggleButton btn_Update;
    private javax.swing.JToggleButton btn_add1;
    private javax.swing.JToggleButton btn_del;
    private javax.swing.JToggleButton btn_restore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlb_authority;
    private javax.swing.JLabel jlb_email;
    private javax.swing.JLabel jlb_firstName;
    private javax.swing.JLabel jlb_lastName;
    private javax.swing.JLabel jlb_phone;
    private javax.swing.JLabel jlb_staff;
    private javax.swing.JLabel jlb_staffID;
    private javax.swing.JTextField sdtJbl;
    private javax.swing.JTable tbl_Staff;
    private javax.swing.JTextField tenkhachJlb;
    private javax.swing.JTextField tenkhachJlb1;
    private javax.swing.JTextField tenkhachJlb2;
    private javax.swing.JTextField txt_authority;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
